=== zeus911/SAVPN_BSNL01/crm.ear/crm.war/WEB-INF/bin/XMLConverter/portal.dtd
<!-- This file is autogenerated by GenDTD based on the 'dtdConfig' file. Do not change this file--> 

<!ELEMENT Table  (#PCDATA)>
<!ELEMENT Tables (Table+)>

<!ELEMENT Sequence  (#PCDATA)>
<!ELEMENT Sequences (Sequence+)>
<!ATTLIST Sequence increment CDATA #IMPLIED>
<!ATTLIST Sequence start CDATA #IMPLIED>

<!ELEMENT CustomerId (#PCDATA)>
<!ATTLIST CustomerId Type CDATA #FIXED "String">

<!ELEMENT CompanyName (#PCDATA)>
<!ATTLIST CompanyName Type CDATA #FIXED "String">

<!ELEMENT CompanyAddress (#PCDATA)>
<!ATTLIST CompanyAddress Type CDATA #FIXED "String">

<!ELEMENT CompanyCity (#PCDATA)>
<!ATTLIST CompanyCity Type CDATA #FIXED "String">

<!ELEMENT CompanyZipCode (#PCDATA)>
<!ATTLIST CompanyZipCode Type CDATA #FIXED "String">

<!ELEMENT ContactpersonName (#PCDATA)>
<!ATTLIST ContactpersonName Type CDATA #FIXED "String">

<!ELEMENT ContactpersonSurname (#PCDATA)>
<!ATTLIST ContactpersonSurname Type CDATA #FIXED "String">

<!ELEMENT ContactpersonPhonenumber (#PCDATA)>
<!ATTLIST ContactpersonPhonenumber Type CDATA #FIXED "String">

<!ELEMENT ContactpersonEmail (#PCDATA)>
<!ATTLIST ContactpersonEmail Type CDATA #FIXED "String">

<!ELEMENT Status (#PCDATA)>
<!ATTLIST Status Type CDATA #FIXED "String">

<!ELEMENT LastUpdateTime (#PCDATA)>
<!ATTLIST LastUpdateTime Type CDATA #FIXED "long">

<!ELEMENT CreationTime (#PCDATA)>
<!ATTLIST CreationTime Type CDATA #FIXED "String">

<!ELEMENT Customer (
    CustomerId,
    CompanyName,
    CompanyAddress,
    CompanyCity,
    CompanyZipCode,
    ContactpersonName,
    ContactpersonSurname,
    ContactpersonPhonenumber,
    ContactpersonEmail,
    Status,
    LastUpdateTime,
    CreationTime,
    ISPARENT__
)>
<!ATTLIST Customer PK CDATA #FIXED "CustomerId">
<!ATTLIST Customer RefName CDATA #FIXED "CustomerId">
<!ATTLIST Customer TableName CDATA #FIXED "crm_customer">

<!ELEMENT ServiceId (#PCDATA)>
<!ATTLIST ServiceId Type CDATA #FIXED "String">

<!ELEMENT PresName (#PCDATA)>
<!ATTLIST PresName Type CDATA #FIXED "String">

<!ELEMENT State (#PCDATA)>
<!ATTLIST State Type (ref|String) "String">

<!ELEMENT SubmitDate (#PCDATA)>
<!ATTLIST SubmitDate Type CDATA #FIXED "String">

<!ELEMENT ModifyDate (#PCDATA)>
<!ATTLIST ModifyDate Type CDATA #FIXED "String">

<!ELEMENT Type (#PCDATA)>
<!ATTLIST Type Type (ref|String) "String">

<!ELEMENT __1__CustomerId (#PCDATA)>
<!ATTLIST __1__CustomerId Type (ref|String) "String">

<!ELEMENT ParentServiceId (#PCDATA)>
<!ATTLIST ParentServiceId Type (ref|String) "String">

<!ELEMENT EndTime (#PCDATA)>
<!ATTLIST EndTime Type CDATA #FIXED "String">

<!ELEMENT NextOperationTime (#PCDATA)>
<!ATTLIST NextOperationTime Type CDATA #FIXED "long">

<!ELEMENT Service (
    ServiceId,
    PresName,
    State,
    SubmitDate,
    ModifyDate,
    Type,
    __1__CustomerId,
    ParentServiceId,
    EndTime,
    NextOperationTime,
    LastUpdateTime,
    ISPARENT__
)>
<!ATTLIST Service PK CDATA #FIXED "ServiceId">
<!ATTLIST Service RefName CDATA #FIXED "ServiceId">
<!ATTLIST Service TableName CDATA #FIXED "crm_service">

<!ELEMENT __1__ServiceId (#PCDATA)>
<!ATTLIST __1__ServiceId Type (ref|String) "String">

<!ELEMENT Attribute (#PCDATA)>
<!ATTLIST Attribute Type CDATA #FIXED "String">

<!ELEMENT Value (#PCDATA)>
<!ATTLIST Value Type CDATA #FIXED "String(4000)">

<!ELEMENT ServiceParameter (
    __1__ServiceId,
    Attribute,
    Value,
    ISPARENT__
)>
<!ATTLIST ServiceParameter PK CDATA #FIXED "__1__ServiceId,Attribute">
<!ATTLIST ServiceParameter RefName CDATA #FIXED "__1__ServiceId,Attribute">
<!ATTLIST ServiceParameter TableName CDATA #FIXED "crm_serviceparam">

<!ELEMENT vpnId (#PCDATA)>
<!ATTLIST vpnId Type (ref|String) "String">

<!ELEMENT siteAttachmentId (#PCDATA)>
<!ATTLIST siteAttachmentId Type (ref|String) "String">

<!ELEMENT ConnectivityType (#PCDATA)>
<!ATTLIST ConnectivityType Type CDATA #FIXED "String">

<!ELEMENT VPNMembership (
    vpnId,
    siteAttachmentId,
    ConnectivityType,
    ISPARENT__
)>
<!ATTLIST VPNMembership PK CDATA #FIXED "vpnId,siteAttachmentId">
<!ATTLIST VPNMembership RefName CDATA #FIXED "vpnId,siteattachmentId">
<!ATTLIST VPNMembership TableName CDATA #FIXED "crm_vpn_membership">

<!ELEMENT ISPARENT__ (#PCDATA)>
<!ATTLIST ISPARENT__ Type CDATA  #FIXED "String"><!ELEMENT ROOT (
  Tables,
  Sequences,
  Customer*,
  Service*,
  ServiceParameter*,
  VPNMembership*
)>

=== zeus911/SAVPN_BSNL01/crm.ear/crm.war/WEB-INF/bin/XMLConverter/export.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ROOT SYSTEM "portal.dtd">
<!--
###############################################################################
#
#  (c) Copyright 2003-2010 Hewlett-Packard Development Company, L.P. 
#
#   
###############################################################################

###############################################################################
#
# $Source: /tmp/vpn/SA_VPN_SP/jboss/server/default/deploy/crmportal.sar/crm.war/WEB-INF/bin/XMLConverter/export.start,v $
# $Revision: 1.8 $
# $Date: 2010-12-14 06:32:30 $
# $Author: shiva $
#
###############################################################################
#
# <Description> 
#
###############################################################################
-->
<ROOT>
  <Tables>
    <Table>crm_customer</Table>
    <Table>crm_service</Table>
    <Table>crm_serviceparam</Table>
    <Table>crm_vpn_membership</Table>
  </Tables>

  <Sequences>
    <Sequence>CRM_CUSTOMER_ID_SEQ</Sequence>
    <Sequence>CRM_MESSAGE_ID_SEQ</Sequence>
    <Sequence>CRM_SERVICE_ID_SEQ</Sequence>
  </Sequences>
  <Customer PK="CustomerId" RefName="CustomerId" TableName="crm_customer">
    <CustomerId    Type="String"></CustomerId>
    <CompanyName    Type="String"></CompanyName>
    <CompanyAddress    Type="String"></CompanyAddress>
    <CompanyCity    Type="String"></CompanyCity>
    <CompanyZipCode    Type="String"></CompanyZipCode>
    <ContactpersonName    Type="String"></ContactpersonName>
    <ContactpersonSurname    Type="String"></ContactpersonSurname>
    <ContactpersonPhonenumber    Type="String"></ContactpersonPhonenumber>
    <ContactpersonEmail    Type="String"></ContactpersonEmail>
    <Status    Type="String"></Status>
    <LastUpdateTime    Type="long"></LastUpdateTime>
    <CreationTime    Type="String"></CreationTime>
    <ISPARENT__    Type="String"></ISPARENT__>
  </Customer>

  <Service PK="ServiceId" RefName="ServiceId" TableName="crm_service">
    <ServiceId    Type="String"></ServiceId>
    <PresName    Type="String"></PresName>
    <State    Type="String"></State>
    <SubmitDate    Type="String"></SubmitDate>
    <ModifyDate    Type="String"></ModifyDate>
    <Type    Type="String"></Type>
    <__1__CustomerId    Type="String"></__1__CustomerId>
    <ParentServiceId    Type="String"></ParentServiceId>
    <EndTime    Type="String"></EndTime>
    <NextOperationTime    Type="long"></NextOperationTime>
    <LastUpdateTime    Type="long"></LastUpdateTime>
    <ISPARENT__    Type="String"></ISPARENT__>
  </Service>

  <ServiceParameter PK="__1__ServiceId,Attribute" RefName="__1__ServiceId,Attribute" TableName="crm_serviceparam">
    <__1__ServiceId    Type="String"></__1__ServiceId>
    <Attribute    Type="String"></Attribute>
    <Value    Type="String(4000)"></Value>
    <ISPARENT__    Type="String"></ISPARENT__>
  </ServiceParameter>

  <VPNMembership PK="vpnId,siteAttachmentId" RefName="vpnId,siteattachmentId" TableName="crm_vpn_membership">
    <vpnId    Type="String"></vpnId>
    <siteAttachmentId    Type="String"></siteAttachmentId>
    <ConnectivityType    Type="String"></ConnectivityType>
    <ISPARENT__    Type="String"></ISPARENT__>
  </VPNMembership>


</ROOT>
